main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls import handler404, handler500

from apps.Login.views import LoginUserView, Error404View, Error500View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="accounts/login")),
    path('accounts/login/', LoginUserView.as_view(), name='custom_login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/registration/', include('apps.Login.urls')),
    path('project/', include('apps.Project.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Esto servirá únicamente cuando el servidor esté en despliegue (DEBUG=False)
handler404 = Error404View.as_view()
handler500 = Error500View.as_view()

apps/Login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.settings import MEDIA_URL, STATIC_URL


class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, default='users/default.jpg')

    def __str__(self):
        # Se presenta el primer nombre y primer apellido y no los dos.
        return '{} {}'.format(self.first_name.split(' ')[0], self.last_name.split(' ')[0])

    def save(self, *args, **kwargs):
        try:
            # Obtenemos la imagen actual para eleminarla y luego guardamos la nueva
            this = User.objects.get(id=self.id)
            if this.profile_picture != self.profile_picture and this.profile_picture != 'users/default.jpg':
                this.profile_picture.delete(save=False)
        except User.DoesNotExist:
            pass
        super(User, self).save(*args, **kwargs)

templates/user/password_change.html
{% extends 'Project/base_project.html' %}
{% load static %}


{% block cssCustoms2 %}
	<link rel="stylesheet" href="{% static "css/dato_personal.css" %}">
	<link rel="stylesheet" href="{% static "css/loader.css" %}">
{% endblock %}


<!-- contenido de la pagina -->
{% block content %}
	<!-- información de la pagína -->
	<div class="container-fluid header-c">
		<div class="row">
			<div class="col-md he-title">
				<h2>CAMBIAR CONTRASEÑA</h2>
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md">
				<p class="info_title">Apartado para cambiar la contraseña del usuario</p>
			</div>
		</div>
	</div>
	<!-- Contenido de la pagína -->
	<div class="container">
		<div class="col-sm-12">
			<div class="">
				<div class=" card card-body">
					<form action="{% url 'password_change' %}" method="post">
						{% csrf_token %}
						<div class="modal-body fondo">
							<label class="form-label fw-bold">Ingrese contraseña actual</label>
							<div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-lock-fill" viewBox="0 0 16 16">
                                    <path
		                                    d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2"/>
                                </svg>
                            </span>
								<input type="password" class="form-control" placeholder="Ingrese contraseña"
								       aria-label="password" aria-describedby="basic-addon1" name="old_password"
								       id="old_password">
							</div>
							<div id="passwordHelpBlock" class="form-text">
								Para poder cambiar de contraseña debe ingresar la contraseña actual con el fin de
								verificación su identidad.
							</div>
							<label class="form-label fw-bold">Ingrese nueva contraseña</label>
							<div class="input-group mb-3">
                            <span class="input-group-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-key" viewBox="0 0 16 16">
                                    <path
		                                    d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8m4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5"/>
                                    <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                                </svg>
                            </span>
								<input type="password" class="form-control" id="new_password1"
								       placeholder="Nueva contraseña"
								       aria-label="password" aria-describedby="basic-addon1" name="new_password1">
							</div>
							<div class="input-group mb-3">
                            <span class="input-group-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-key-fill" viewBox="0 0 16 16">
                                    <path
		                                    d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2M2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
                                </svg>
                            </span>
								<input type="password" class="form-control" id="new_password2" name="new_password2"
								       placeholder="Confirmar contraseña" aria-label="password"
								       aria-describedby="basic-addon1">
							</div>
							<div id="mensaje_validacion" class="form-text mt-2"></div>
							<!-- Mensaje de validación -->
							<div class="form-text">
								Ingrese correctamente la nueva contraseña.
							</div>
						</div>
						<div class="modal-footer fondo d-flex justify-content-center">
							<button type="submit" class="btn btn_primary m-1 col-auto">Confirmar
							</button>
							<a href="{% url 'update_user' user.id %}" class="btn btn_warning m-1 col-auto">Cancelar
							</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	{% if form.errors %}
		<div id="bodyAlertPlaceholder" class="fixed-button">
			<div>
				<div class="alert alert-success alert-dismissible" role="alert">
					<div>{{ form.errors }}</div>
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}

<!-- Modal's -->
{% block modals %}

{% endblock modals %}

{% block js %}
	<script src="{% static "js/menu.js" %}"></script>
	<script src="{% static "js/datos_personales.js" %}"></script>
{% endblock js %}

templates/user/update_user.html
{% extends 'Project/base_project.html' %}
{% load static %}


{% block cssCustoms2 %}
	<link rel="stylesheet" href="{% static "css/dato_personal.css" %}">
	<link rel="stylesheet" href="{% static "css/loader.css" %}">
{% endblock %}


<!-- contenido de la pagina -->
{% block content %}
	<div class="header-c">
		<div class="row">
			<div class="col-md he-title">
				<h2>DATOS PERSONALES</h2>
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md">
				<p class="info_title">Información de los datos personales del usuario.</p>
			</div>
		</div>
	</div>
	<!-- Contenido de la pagina -->
	<div class="body-c">
		<div class="container_content d-flex align-items-center justify-content-center">
			<div class="row">
				<div class="col-4 image_container">
					<div class="center">
						<img id="image_profile" class="image_edit" src="{{ user.profile_picture.url }}" alt="Imagen 
						usuario">
					</div>
					<h5 class="text-center"><strong class="text_warning">Foto</strong> de perfil</h5>
				</div>
				<div class="col">
					<div class="h2 pb-2 mb-4 text_info border-bottom border-3 border-primary">
						Bienvenido, {{ user }}!
					</div>
					<form method="post" action="{{ action_save }}" enctype="multipart/form-data">
						<input type="hidden" name="action" value="{{ action }}">
						{% csrf_token %}
						<div class="card_form row justify-content-end align-items-center">
							<div class="row">
								<div class="col">
									<div class="input-group form_shadow mb-3">
                        <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                            </svg>
                        </span>
										<input type="text" class="form-control" aria-label="Username"
										       aria-describedby="basic-addon1" name="username" id="id_username"
										       value="{{ form.username.value }}" required>
									</div>
								</div>
								<div class="col">
									<div class="input-group form_shadow mb-3">
                        <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                            </svg>
                        </span>
										<input type="text" class="form-control" aria-label="Username"
										       aria-describedby="basic-addon1" name="first_name" id="id_first_name"
										       value="{{ form.first_name.value }}" required>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col">
									<div class="input-group form_shadow mb-3">
                        <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                            </svg>
                        </span>
										<input type="text" class="form-control" aria-label="Username"
										       aria-describedby="basic-addon1" name="last_name" id="id_last_name"
										       value="{{ form.last_name.value }}" required>
									</div>
								</div>
								<div class="col">
									<div class="input-group form_shadow mb-3">
                        <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
                            </svg>
                        </span>
										<input type="email" class="form-control" aria-label="Username"
										       aria-describedby="basic-addon1" name="email" id="id_email"
										       value="{{ form.email.value }}" required>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col">
									<div class="input-group form_shadow mb-3">
                        <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-image-fill" viewBox="0 0 16 16">
                                <path d="M.002 3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-12a2 2 0 0 1-2-2zm1 9v1a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V9.5l-3.777-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062zm5-6.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
                            </svg>
                        </span>
										<input class="form-control" type="text" id="fileName"
										       readonly placeholder="{{ form.profile_picture.value }}">
										<input class="form-control" type="file" accept="image/*"
										       id="id_profile_picture" name="profile_picture"
										       style="display: none;">
										<button
												class="btn btn_subirfoto col-auto d-flex justify-content-center align-items-center button"
												type="button" id="uploadButton">
											<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
											     fill="currentColor" class="bi bi-capslock-fill" viewBox="0 0 16 16">
												<path
														d="M7.27 1.047a1 1 0 0 1 1.46 0l6.345 6.77c.6.638.146 1.683-.73 1.683H11.5v1a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-1H1.654C.78 9.5.326 8.455.924 7.816zM4.5 13.5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1z"/>
											</svg>
										</button>
									</div>
								</div>
								<div class="col">
									<div class="input-group mb-3">
										<a href="{% url 'password_change' %}" class="btn btn_primary col">
											<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
											     fill="currentColor" class="bi bi-person-fill-lock" viewBox="0 0 16 16">
												<path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-9 8c0 1 1 1 1 1h5v-1a2 2 0 0 1 .01-.2 4.49 4.49 0 0 1 1.534-3.693Q8.844 9.002 8 9c-5 0-6 3-6 4m7 0a1 1 0 0 1 1-1v-1a2 2 0 1 1 4 0v1a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1zm3-3a1 1 0 0 0-1 1v1h2v-1a1 1 0 0 0-1-1"/>
											</svg>
											Cambiar clave
										</a>
									</div>
								</div>
							</div>
							<div class="row justify-content-end mt-4">
								<button type="submit" class="btn btn_primary m-2 col-auto fw-bold">Actualizar</button>
								<a href="{% url 'update_user' user.id %}" class="btn btn_warning m-2 col-auto fw-bold">Cancelar</a>
							</div>
						</div>
					</form>

					{% if messages %}
						<div id="bodyAlertPlaceholder" class="fixed-button">
							{% for message in messages %}
								<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
									<div>{{ message }}</div>
									<button type="button" class="btn-close" data-bs-dismiss="alert"
									        aria-label="Close"></button>
								</div>
							{% endfor %}
						</div>
					{% endif %}
					{% if form.errors %}
						<div id="bodyAlertPlaceholder" class="fixed-button">
							<div>
								<div class="alert alert-danger alert-dismissible" role="alert">
									{% for field, errors in form.errors.items %}
										{% for error in errors %}
											<div>
												{{ error }}
											</div>
										{% endfor %}
									{% endfor %}
									<button type="button" class="btn-close" data-bs-dismiss="alert"
									        aria-label="Close"></button>
								</div>
							</div>
						</div>
					{% endif %}

				</div>
			</div>
		</div>
	</div>

{% endblock %}

<!-- Modal's -->
{% block modals %}

{% endblock modals %}

{% block js %}
	<script src="{% static "js/menu.js" %}"></script>
	<script src="{% static "js/datos_personales.js" %}"></script>
{% endblock js %}